stages:
  - build
  - test
  - review
  - staging
  - production
  - post_deploy
  - tag_latest

build:
  stage: build
  extends: .build_template

container_scan:
  stage: test
  extends: .container_scan_template

loadtest:
  stage: post_deploy
  extends: .loadtest_template

review:
  stage: review 
  extends: .review_template

review_stop:
  stage: review 
  extends: .review_stop_template

staging:
  stage: staging
  extends: .staging_template

production:
  stage: production
  extends: .production_template

tag_latest:
  stage: tag_latest 
  extends: .tag_latest_template

.common:
  tags_template: &tags
    tags:
      - mintel
  docker_template: &docker
    services: 
      - docker:stable-dind
    variables:
      DOCKER_DRIVER: overlay2

.build_template:
  <<: *tags
  <<: *docker
  stage: 
    build
  script:
    - command build
  only:
    - branches

.container_scan_template:
  <<: *tags
  <<: *docker
  stage: test
  allow_failure: false
  script:
    - command container_scan
  except:
    variables:
      - $CONTAINER_SCANNING_DISABLED

.loadtest_template:
  <<: *tags
  stage: post_deploy
  allow_failure: true
  script:
    - command loadtest
  when: manual
  only:
    - master
  environment:
    name: production
  except:
    variables:
      - $LOADTEST_DISABLED

.review_template:
  <<: *tags
  stage: review
  script:
    - command deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: review_stop
  when: manual
  only:
    - branches
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

.review_stop_template:
  <<: *tags
  stage: review
  script:
    - command destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    refs:
      - master
    variables:
      - $REVIEW_DISABLED

.staging_template:
  <<: *tags
  stage: staging
  script:
    - command deploy
  environment:
    name: staging
  only:
    - master
  except:
    variables:
      - $STAGING_DISABLED

.production_template:
  <<: *tags
  stage: production
  script:
    - command deploy
  environment:
    name: production
  when: manual
  allow_failure: false
  only:
    - master
  except:
    variables:
      - $PRODUCTION_DISABLED

.tag_latest_template:
  <<: *tags
  <<: *docker
  stage: tag_latest
  allow_failure: false
  script:
    - command push
  only:
    - master
  except:
    variables:
      - $TAG_LATEST_DISABLED
