stages:
  - build
  - test
  - tag-image
  - pre-deploy

build:
  stage: build
  extends: .build_template

tag-review:
  stage: tag-image
  extends: .tag_review_template

tag-staging:
  stage: tag-image
  extends: .tag_staging_template

tag-production:
  stage: tag-image
  extends: .tag_production_template

container-scan:
  stage: test
  extends: .container_scan_template

.common:
  tags_template: &tags
    tags:
      - mintel
  docker_template: &docker
    services: 
      - docker:stable-dind
    variables:
      DOCKER_DRIVER: overlay2

.build_template:
  <<: *tags
  <<: *docker
  stage: 
    build
  script:
    - command build_image
  only:
    - branches
    - tags

.container_scan_template:
  <<: *tags
  <<: *docker
  stage: test
  allow_failure: false
  script:
    - command container_scan
  except:
    variables:
      - $CONTAINER_SCANNING_DISABLED

.tag_review_template:
  <<: *tags
  <<: *docker
  stage: tag-image
  allow_failure: false
  script:
    - command publish_image review
  only:
    - branches
  except:
    refs:
      - master
      - production
    variables:
      - $TAG_REVIEW_DISABLED

.tag_staging_template:
  <<: *tags
  <<: *docker
  stage: tag-image
  allow_failure: false
  script:
    - command publish_image staging
  only:
    - master
  except:
    variables:
      - $TAG_STAGING_DISABLED

.tag_production_template:
  <<: *tags
  <<: *docker
  stage: tag-image
  allow_failure: false
  script:
    - command publish_image production
  only:
    refs:
      - tags
      - /^production$
  except:
    variables:
      - $TAG_PRODUCTION_DISABLED

.loadtest_template:
  <<: *tags
  allow_failure: false
  script:
    - command loadtest
  only:
    - master
    - tags
  except:
    variables:
      - $LOADTEST_DISABLED
