stages:
  - build
  - test
  - tag-image
# - pre-deploy
  - deploy
  - post-deploy

build:
  stage: build
  extends: .build_template

tag-review:
  stage: tag-image
  extends: .tag_review_template

tag-staging:
  stage: tag-image
  extends: .tag_staging_template

tag-production:
  stage: tag-image
  extends: .tag_production_template

container-scan:
  stage: test
  extends: .container_scan_template

deploy-review:
  stage: deploy
  extends: .review_template

deploy-review-delete:
  stage: deploy
  extends: .review_delete_template

deploy-staging:
  stage: deploy
  extends: .staging_template

deploy-production:
  stage: deploy
  extends: .production_template

loadtest:
  stage: post-deploy
  extends: .loadtest_template

.common:
  tags_template: &tags
    tags:
      - mintel
  docker_template: &docker
    services: 
      - docker:stable-dind
    variables:
      DOCKER_DRIVER: overlay2

.build_template:
  <<: *tags
  <<: *docker
  stage: 
    build
  script:
    - command build_image
  only:
    - branches

.container_scan_template:
  <<: *tags
  <<: *docker
  stage: test
  allow_failure: false
  script:
    - command container_scan
  except:
    variables:
      - $CONTAINER_SCANNING_DISABLED

.tag_review_template:
  <<: *tags
  <<: *docker
  stage: tag-image
  allow_failure: false
  script:
    - command publish_image review
  only:
    - branches
  except:
    variables:
      - $TAG_REVIEW_DISABLED

.tag_staging_template:
  <<: *tags
  <<: *docker
  stage: tag-image
  allow_failure: false
  script:
    - command publish_image staging
  only:
    - master
  except:
    variables:
      - $TAG_STAGING_DISABLED

.tag_production_template:
  <<: *tags
  <<: *docker
  stage: tag-image
  allow_failure: false
  script:
    - command publish_image production
  only:
    - tags
  except:
    variables:
      - $TAG_PRODUCTION_DISABLED

.loadtest_template:
  <<: *tags
  allow_failure: false
  script:
    - command loadtest
  only:
    - master
    - tags
  except:
    variables:
      - $LOADTEST_DISABLED

.review_template:
  <<: *tags
  stage: deploy
  script:
    - command deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: deploy-review-delete
  artifacts:
    paths:
      - ci-vars/vars.txt
  when: manual
  only:
    - branches
  except:
    variables:
      - $REVIEW_DISABLED

.review_delete_template:
  <<: *tags
  stage: deploy
  script:
    - command destroy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    variables:
      - $REVIEW_DISABLED

.staging_template:
  <<: *tags
  stage: deploy
  script:
    - command deploy staging
  environment:
    name: staging
  artifacts:
    paths:
      - ci-vars/vars.txt
  only:
    - master
  except:
    variables:
      - $STAGING_DISABLED

.production_template:
  <<: *tags
  stage: deploy
  script:
    - command deploy production
  environment:
    name: production
  artifacts:
    paths:
      - ci-vars/vars.txt
  when: manual
  allow_failure: false
  only:
    - tags
  except:
    variables:
      - $PRODUCTION_DISABLED
