.common:
  tags_template: &tags
    tags:
      - mintel
  docker_template: &docker
    services: 
      - docker:stable-dind
    variables:
      DOCKER_DRIVER: overlay2

.build_template:
  <<: *tags
  <<: *docker
  stage: 
    build
  script:
    - command build
  only:
    - branches

.container_scan_template:
  <<: *tags
  <<: *docker
  stage: test
  allow_failure: false
  script:
    - command container_scan
  except:
    variables:
      - $CONTAINER_SCANNING_DISABLED

.loadtest_template:
  <<: *tags
  allow_failure: false
  script:
    - command loadtest
  only:
    - master
  except:
    variables:
      - $LOADTEST_DISABLED
